### ISSUE TITLE
Translating in Japanese

### ISSUE THREAD

**Issue by AlixFachin** [eslint/eslint.org#164]
### What language do you want to translate the website into?

Japanese

### What is the language code for the language?

ja

### What is the locale code for the language?

JP

### What help will you need?

I will need a bit of time but I'll do my best!

### Implementation Checklist

- [x] Create new site file
- [x] Set up Netlify project
- [x] Register new domain name
- [ ] Set up Google Analytics
- [ ] Set up Carbon Ads

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Thanks! Is the issue title incorrect?

**Comment by AlixFachin** [comment]
Woops. I tried to create another issue at the same time.
(Not sure if this is the right place, I'll delete this comment otherwise.
I spent a few hours before being able to run the website locally on the ARM64 architecture. I thought I would open an issue to give details about how to do it as it would help other people. Should I rather open a new issue for this, or create a pull request adding something to the README file?)

**Comment by nzakas** [comment]
If there’s a problem you can’t solve, then please open another issue. If there’s something you figured out to make it work, then a PR to the README would be great.

**Comment by nzakas** [comment]
@AlixFachin are you still working on this?

**Comment by nzakas** [comment]
No problem! Just wanted to know if we should ask for other volunteers to help out.

**Comment by AlixFachin** [comment]
The more the merrier?

Maybe I can already create a pull request so that other people can comment on the traduction quality, and see what remains to be done?

Quick questions:
a) Should I / can I remove lines not relevant to Japanese (e.g. "Donate to a 501(c)(3) non-profit", if this has to do with US-specific tax setting, maybe not relevant in Japan?)
b) Just to confirm -> I need to figure out a way to translate the content without having to change the layout (e.g. the "dark"/"regular" theme color switcher doesn't really fit Japanese characters, I will have to figure out a shorter word!)

**Comment by nzakas** [comment]
@AlixFachin sure! Creating a PR with your current work would give others the opportunity to chime in. Just mark it as a "draft" to indicate it's not quite ready.

With regards to your questions:

1. Please translate everything as-is, even if it doesn't seem relevant. People in the U.S. might also switch to the Japanese version, and trying to keep track of variations per region will be too difficult for us.
2. That's correct. In the case of theme switcher, we should hopefully be able to adjust it so that the buttons grow to the correct size to support the content. If you can send a PR with what you have so far, I can take a look locally and see how we can adjust the CSS.

Thanks!

**Comment by nzakas** [comment]
The site is live: https://ja.eslint.org/

Please take a look and verify everything looks correct.

I'll work on getting the analytics and ads configured.

**Comment by nzakas** [comment]
Adding analytics in #202.

**Comment by nzakas** [comment]
This is complete, so closing.
