### ISSUE TITLE
Update dropdown markup for accessibility

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint.org#279]
Pulling from https://github.com/eslint/play.eslint.org/pull/6#issuecomment-1083163991, just so we don't forget:

> @snitin315 The problem isn't with the styles, it's with the markup. The code isn't accessible and it's also not even properly operable by keyboard. Styles can be overridden but the markup is where the accessibility is built into. Changing the styles is not enough.

Oh, I see. I will work on migrating to the accesible select component you provided once everything else is done.

**Comment by nzakas** [comment]
@snitin315 are you still planning on addressing this?

**Comment by snitin315** [comment]
I don't see myself working on it in near future. But we have two options to go with -

-  Refactor the [old select component](https://github.com/eslint/playground/blob/23bea25563ee62306ede0ade6e0a8641979ed84a/src/assets/js/select.js#L11) to make it work with react. This seems to be a high-effort task.
- [Explore accessibility with the current `react-select`](https://react-select.com/advanced#accessibility) library. Much simpler since the component is already implemented.

**Comment by harish-sethuraman** [comment]
I can pick this up 😄

**Comment by snitin315** [comment]
@harish-sethuraman Thanks, feel free to ask anything if needed.

**Comment by nzakas** [comment]
Thanks @harish-sethuraman. I believe you should look at this commit for the original version: https://github.com/eslint/playground/commit/178f9fd66e6bdffe944f74665634c8ca11fbf045

**Comment by harish-sethuraman** [comment]
So I was trying to use the dropdown with keyboard and it seems to work perfectly? I'm able to select, move and open dropdown and close it via keyboard. I'd like to know what more we are trying to add here? 😅

**Comment by nzakas** [comment]
I believe Sara mentioned some concerns on the PR I referenced.

**Comment by nzakas** [comment]
Seems like concerns were addressed, so closing.
