### ISSUE TITLE
Suggestion: merge main site and docs site into one

### ISSUE THREAD

**Issue by kecrily** [eslint/eslint.org#320]
## Motivation

Currently, the eslint/eslint repository has a lot of content that is not related to the core, such as the style and layout of the documents.

And there are some styles and utilities that can be shared between the documentation site and the main site. However, they have to be implemented twice because they are separated in two repositories.

## How to do it

Merge the docs directory of eslint/eslint into this. Use `git filter-branch` to keep records.

## Roadmap if plan to merge

1. Migrate files completely unmodified, like playground as a separate project
2. Keep only one of the redundant reusable files
3. Fully integrated

## Q&A

- Q: What if I add/modify a rule while developing ESLint and need to make changes to the rule document at the same time?
  A: Just add a script to `package.json` to ` git sparse-checkout` from this repository[^1]. It is executed when a document needs to be modified, and then only the document associated with the rule is checkout and modified.

## Others

If a language does not have a separate repository, create field translations in this repository. If there is a separate repository, use this repository as an upstream, and the separate language repository is equivalent to the fork of this repository.

[^1]: [git-sparse-checkout Documentation - Git](https://git-scm.com/docs/git-sparse-checkout)

**Comment by nzakas** [comment]
We intentionally keep the docs and the main website separate. This was a key part of the redesign due to past pain points.

**Comment by nzakas** [comment]
Oops, sorry, hit submit too soon. 

I agree with the concern over duplicating style elements in both places, but I think there are other ways to solve this problem. For instance, we could make eslint.org and installable package with the shared assets. Then the docs site could use that as a dependency and copy over what it needed.

**Comment by kecrily** [comment]
> This was a key part of the redesign due to past pain points.

Can you explain this point?

**Comment by nzakas** [comment]
We have gone through several stages:

1. when ESLint first started, the docs were in the website repo. The problem was that we couldn’t get people to update the docs. No one wanted to submit a second pull request to a different repository after their feature was merged.
2. We moved the docs into the ESLint repo but it was just the Markdown files. This made it easy for people to submit documentation with their features. We would then copy the markdown files to the website repo during the release. This approach had several problems: 1) we were limited in how we could format the documentation because we didn’t have CSS or HTML layouts in the eslint repo, 2) we could easily preview docs changes locally, 3) new contributors would try to update the docs in the website repo not realizing they would be overwritten at the next release, so we constantly had to ask people to submit the changes in two locations.

When we did the redesign, a goal was to have the docs site live completely in the eslint repo to solve the problems with approach #2. We knew there would be some duplication of UI elements, but we felt that was an acceptable tradeoff because it’s easier to move UI around when necessary.

**Comment by aladdin-add** [comment]
what do you think the way of monorepos? some popular projects like vite.js, ts-eslint have been already using it for a while.

the downside is we have to update our release tool to support it, or choose another one.

**Comment by kecrily** [comment]
> 1. when ESLint first started, the docs were in the website repo. The problem was that we couldn’t get people to update the docs. No one wanted to submit a second pull request to a different repository after their feature was merged.

I mentioned above that we can use `git sparse-checkout` in the eslint repo so that people can edit the document without leaving the working directory and will focus on the md file. This effectively makes the `docs/` directory a mirror of one of the directories in this repository. This way, changes to the `docs/` directory are also synchronized to this repository in real time

**Comment by nzakas** [comment]
I’m sorry, I don’t believe git sparse-checkout is a good option here. We put a lot of thought into the current setup, and aside from needing to find a good way to share UI components, I don’t think it’s worth reorganizing things again at this point.

Keep in mind, each version’s docs are deployed as a separate site which makes it easy to switch between them. Copying just the current docs over into the eslint.org repo  would further complicate this approach.

I’d rather spend the time focusing on how to share UI components across the sites.

**Comment by kecrily** [comment]
In that case, let's abandon that idea and look instead for ways to share components across repositories.
