### ISSUE TITLE
Suggestion: Be more clear in differentiating "formatting" vs "style"

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [eslint/eslint.org#419]
### What problem do you want to solve?

On typescript-eslint.io, we generally use the following vocabulary to describe areas of lint rule responsibilities:

* 💩 **Formatting**: Rules that care only about trivia (semicolons, whitespace, etc.) without impacting the runtime behavior of the code. These rules conflict with dedicated formatters such as Prettier.
* 💅 **Stylistic**: Rules that care about style concerns which _do_ impact runtime behavior of code, but generally not _logic_. These are mostly around naming or which roughly-equivalent syntax constructs to use (such as function declarations vs. arrow functions).
* 🧠 **Logical**: Rules that care about the logic in runtime behavior of code.
 
However, https://eslint.org/blog/2020/05/changes-to-rules-policies/#what-are-the-changes%3F [^1] -which we link to in the [typescript-eslint _What About Formatting?_ page](https://typescript-eslint.io/linting/troubleshooting/formatting/)- uses _"stylistic"_ to describe both what we call 💩 _"formatting"_ and 💅 _"stylistic"_:

> **Stylistic rules are frozen** - we won’t be adding any more options to stylistic rules. We’ve learned that there’s no way to satisfy everyone’s personal preferences, and most of the rules already have a lot of difficult-to-understand options. Stylistic rules are those related to spacing, conventions, and generally anything that does not highlight an error or a better way to do something.

As a reader of that post, I'm actually now not sure - has ESLint frozen what we call  💅 _"stylistic"_ rules? Or are both  💩 _"formatting"_ and 💅 _"stylistic"_ frozen?

Has the ESLint team been intentional about vocabulary in this area?

* If so: what is the system you use?
* If not: can I suggest using the typescript-eslint nomenclature of 💩 _formatting_ vs. 💅 _stylistic_ vs. 🧠 _logical_, and letting me send a PR to amend that blog post? 

[^1]: Original PR adding the ESLint blog post: https://github.com/eslint/archive-website/pull/732

### What do you think is the correct solution?

I'm a fan of 💩 _formatting_ vs. 💅 _stylistic_ vs. 🧠 _logical_ as the nomenclature. Many -in my experience, _most_!- developers don't have strong grasp of the conceptual differences between 💩 _formatting_ and 💅 _stylistic_, even if they understand generally the differences between formatters and linters.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

I realize the silliness of suggesting vocabulary changes to a nearly 3 year old blog post 😄. But this shared vocab is something that would really benefit our work in explaining the differences between formatting & linting concerns.

Corresponding typescript-eslint issue: https://github.com/typescript-eslint/typescript-eslint/issues/6495

**Comment by nzakas** [comment]
By "stylistic", we mean anything that enforces a preference, which could be formatting or, as you point out, something that could affect runtime behavior but isn't necessarily a problem (like `vars-on-top`). If it would help to add that to README, feel free to submit a PR.

Our problem as maintainers is that we keep getting little nitpicky options suggested to support someone's personal preferences, because on a Thursday that also falls on a full moon indents should be two spaces but every other day it should be three spaces. We just don't want to keep adding exceptions to support every possible preference.

Eventually, I'd like to get rid of these rules altogether as I think they are generally a waste of time to build and maintain when you can just use a source code formatter, but in the meantime, we keep them for people to use but we don't want to maintain them.

I really don't want to start introducing new terms or changing the meanings of terms at this point. We already have too many and during the rewrite I'd like to go through and be more intentional about which terms we use and why.

**Comment by JoshuaKGoldberg** [comment]
👍 perfect, thanks @nzakas! I think we're using a fairly similar shared vocab - the blog post is referring to _"stylistic"_ as both formatting & styles. I can just update the typescript-eslint.io docs site to mention this.
