### ISSUE TITLE
Suggestion: Add an explicit page with the recommendation against formatting/style rules

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [eslint/eslint.org#435]
### What problem do you want to solve?

Continuing https://github.com/eslint/eslint.org/issues/419: much of ESLint's community still uses ESLint for formatting logic. Two common user behaviors that are explicitly recommended against by at least me are:

* Directly using ESLint's formatting rules ([`max-len`](https://eslint.org/docs/latest/rules/max-len),[ `semi`](https://eslint.org/docs/latest/rules/semi), etc.)
* Using [`eslint-plugin-prettier`](https://github.com/prettier/eslint-plugin-prettier) to run Prettier through ESLint

I'm under the impression that at least the first of those two, using ESLint's formatting rules, is something the ESLint team explicitly recommends against (e.g. https://github.com/eslint/eslint.org/issues/419#issuecomment-1437511290). At the very least we recommend against it in https://typescript-eslint.io/linting/troubleshooting/formatting.

And I've been recommending against the `eslint-plugin-prettier` option because it slows formatting down to the speed of linting (which is particularly irksome on projects that enable slower, more powerful type checked rules).

### What do you think is the correct solution?

Could we have an explicit notice somewhere on eslint.org indicating _suggestions_ for how to use ESLint properly? How about a _Configuration FAQs_ page with an entry for each of the two points mentioned here?

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by aladdin-add** [comment]
It's fine to state its cons. but I'm not an enthusiastic fan to against this usage. actually, i can see both sides:

Pros:
* Totally configurable (compared to prettier).
* Easier to use, one tool to linting and formatting.

I remember @antfu wrote an article: https://antfu.me/posts/why-not-prettier. :)

**Comment by antfu** [comment]
As a user, I am very fond of ESLint's rules design that allows you to do anything with the AST. Fully customizable and extendable (via custom rules/plugins), making ESLint very powerful and attractive. @aladdin-add already stated the main two points in my mind - being able to use one config + one command to set up ESLint for both linting and formatting is a very good experience.

As a maintainer of many projects, I do understand the maintenance burden on this, and I can relate to the feeling of handling a sea of nitpicking requests. So I am totally up to the decision ESLint made to freeze the stylistic rules and leave it to the community.

But I think saying "against" stylistic rules and recommending Prettier is not an ideal solution as Prettier is an opinionated tool and does not fit very well with ESLint philosophy. A statement like that feels like a 1 and 0, implicitly delivering the message of "you are doing it wrong, and you should use Prettier" making it seems there is no middle ground.

I wish there could be a more configurable, less-opinionated Prettier alternative to recommended - but honestly, I expect it ends up being very similar to what ESLint is like right now. So to me, regardless, there is a "Lint" in the name. The core of ESLint is actually an AST checker and transformer, which is capable of doing some formatting jobs.

So, IMHO, the docs should say something like:

> The **builtin** stylistic rules are frozen and might not cover all the cases **due to the maintenance priority**. If you have very strict styling needs, we recommend you look for community stylistic rules, or use a standalone formatter like Prettier instead.

to directly state the reasoning and caveat, and let users do judge themselves (I think ESLint already says similar in a few places).

---

And as it how it reads, I use ESLint solely for formatting since day one, and I never had formatting/stylistic issues - even if I do have some nitch needs, I wrote plugins with I believe it's how ESLint is supposed to be used. 

Finally, I would like to take this chance to say a big **THANK YOU** for making and maintaining ESLint and those rules. They literally improve my productivity every single day, and I can't imagine how to code without them. It's amazing!
