### ISSUE TITLE
Suggestion: [playground] IDE-style flat config editor

### ISSUE THREAD

**Issue by karlhorky** [eslint/eslint.org#558]
### What problem do you want to solve?

Hi, first of all, thanks for the continuing effort in the ESLint / static analysis ecosystem, really amazing what this enables for all developers, including beginner students like ours 🙌

The Playground currently doesn't have a full IDE-style editor for the configuration, which makes it challenging to add and edit more complex configuration

https://github.com/eslint/eslint.org/assets/1935696/8bb45578-02a4-402d-9c8f-a4fe3cbd0860

### What do you think is the correct solution?

It would be great if there would be an IDE-style editor for the Flat Config, similar to what `typescript-eslint` has for its Playground (although the `typescript-eslint` Playground doesn't yet support the Flat Config):

https://github.com/eslint/eslint.org/assets/1935696/b07e6f56-54ac-4dc0-9700-e3d56d691e37

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
The reason we don't do that is because flat config is all JavaScript, which turns into a security issue when running inside of a web application. Because we can't support everything people would want to do with flat config inside of a browser, we just use the basic options that we know we can properly support.
