### ISSUE TITLE
Bug: Monospace hard to read for "fi"

### ISSUE THREAD

**Issue by Krinkle** [eslint/eslint.org#577]
### URL(s)

https://eslint.org/blog/2022/08/new-config-system-part-2/

### What did you do?

The monospace font seems to have some kind of smart ligatures enabled, that I suspect might be unintended in code context. Please ignore if intended and working as expected, but imho it's hard to read and distracting from the content. It seems like the gap after it is larger and still assuming the absence of smart ligatures. 

### What did you expect to happen?

 -

### What actually happened?

<img height="300" src="https://github.com/eslint/eslint.org/assets/156867/cc9b169f-15f1-44a2-94f6-b60ba2e2ba42">

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by Krinkle** [comment]
Interesting, the pre block below this on the same page is unaffected.

![IMG_9036](https://github.com/eslint/eslint.org/assets/156867/d0b4a4a3-f2e4-4ccf-b8e3-b1c1c2e43e71)

**Comment by fasttime** [comment]
Thanks for the report @Krinkle, I can reproduce this in all browsers. I believe the problem is the [Space Mono](https://fonts.google.com/specimen/Space+Mono) font that renders `fi` and `fl` with a ligature by default (see [this discussion](https://news.ycombinator.com/item?id=11933074)).

We should probably disable ligatures in CSS by setting the `font-variant-ligatures` property to `none` ([reference](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures)). The reason why code blocks on the same page are not affected by this problem despite using the same font is that they already have `font-variant-ligatures: none` in their styles:

https://github.com/eslint/eslint.org/blob/84ef8601bbebbb7ea8b5e99ef97266176a36fc7b/src/assets/scss/syntax-highlighter.scss#L1-L25
